site_name: PocketSOC Documentation
site_description: Documentation for pocketsoc setup

theme:
  name: material
  language: en
  features:
    - content.code.copy


nav:
  - Home: index.md
  - Deployment: deployment.md
  - Design: design.md
  - Access: access.md
  - Exercise 1: exercise_one.md
  - Exercise 2: exercise_two.md
  - Exercise 3: exercise_three.md
  - Exercise 4: exercise_four.md
  - Exercise 5: exercise_five.md
  - Exercise 6: exercise_six.md
  - About : about.md

#repo_url: https://github.com/my-repo/project
#repo_name: "GitHub"

plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/azahmd"  target="_blank" rel="noopener">PocketSOC</a>
