site_name: PocketSOC Documentation
site_description: Documentation for pocketsoc setup

theme:
  name: material
  language: en
  features:
    - content.code.copy


nav:
  - Home: index.md
  - Deployment: deployment.md
  - Design: design.md
  - Access: access.md
  - Troubleshooting: common_issues.md
  - About : about.md

#repo_url: https://github.com/my-repo/project
#repo_name: "GitHub"

plugins:
  - search
