site_name: PocketSOC Documentation
site_description: Documentation for pocketsoc setup

theme:
  name: material
  language: en
  features:
    - content.code.copy


nav:
  - Home: index.md
  - Admin:
    - Deployment: Admin/deployment.md
    - Design: Admin/design.md
  - Trainees:
    - Access: Trainees/access.md
    - Exercise 1: Trainees/exercise_one.md
    - Exercise 2: Trainees/exercise_two.md
    - Exercise 3: Trainees/exercise_three.md
    - Exercise 4: Trainees/exercise_four.md
    - Exercise 5: Trainees/exercise_five.md
    - Exercise 6: Trainees/exercise_six.md


#repo_url: https://github.com/my-repo/project
#repo_name: "GitHub"

plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/azahmd"  target="_blank" rel="noopener">PocketSOC</a>
